### PR TITLE
Adding ESB-Analytics feature.

### PR DESCRIPTION
**Pull request by wggihan**
This feature will allow to install ESB-Analytics feature on DAS 3.1.0

### CODE REVIEW

**Review by thusithathilina — COMMENTED** [review]
I checked the PR against the esb-analytics feature pom. Seems some features are missing in the PR
e..g org.wso2.carbon.analytics:org.wso2.carbon.analytics.core.feature 1.2.3
Could you please check all the features are available in the PR

**Comment by wggihan** [comment]
I checked this feature with DAS 3.1.0 and it worked as expected. This feature is intended to install DAS 3.1.0 only. Do we need to add org.wso2.carbon.analytics:org.wso2.carbon.analytics.core.feature as well in the p2 repo in that case?

**Comment by thusithathilina** [comment]
org.wso2.carbon.analytics:org.wso2.carbon.analytics.core.feature version 1.2.3 is packed with the analytics-esb. Likewise all the features which are packed with the product need to be available in the p2.

**Comment by thusithathilina** [comment]
Closing this PR due to conflicts. This is fix with https://github.com/wso2/carbon-feature-repository/pull/64

**Pull request closed without merging**
